#!/bin/bash

set -e

[ -z "$DATADIR" ] && DATADIR="/var/lib/acme-tiny-wrapper"
[ -z "$CONFIG" ] && CONFIG="/etc/acme-tiny-wrapper"
[ -z "$ACME_TINY_BIN" ] && ACME_TINY_BIN="acme-tiny"

CONFIGFILE="$CONFIG/acme-tiny.cfg"
[ -e $CONFIGFILE ] && source "$CONFIGFILE"
[ -z "$ACME_DIR" ] && ACME_DIR="/srv/www/acme-challenges/"

ACCOUNT_KEY="${CONFIG}/account.key"
INTERMEDIATE="${DATADIR}/intermediate.pem"

curl -o "${INTERMEDIATE}" https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem

for csr in ${CONFIG}/csr/*.csr
do
    name="$(basename "$csr")"
    name="${name%.csr}"
    work_dir="${DATADIR}/certs/${name}"
    CERT="${work_dir}/cert.pem"
    FULLCHAIN="${work_dir}/fullchain.pem"

    mkdir -p "$work_dir"

    ${ACME_TINY_BIN} --account-key "$ACCOUNT_KEY" --csr "$csr" --acme-dir "$ACME_DIR" > "${CERT}.tmp"
    mv -f "${CERT}.tmp" "${CERT}"
    cat "${CERT}" "${INTERMEDIATE}" > "${FULLCHAIN}"

    # Check for location specification
    if [ -e "${name%.csr}.location" ]; then
       cp "${FULLCHAIN}" "$(cat "${name%.csr}.location")"
    elif [ -n "${DEFAULT_LOCATION}" ]; then
       cp "${FULLCHAIN}" "${DEFAULT_LOCATION}"
    fi

done
